Repository Frosty1940/The-Great-War-Redux-Korean, pull requests merged in 2020-12, with the labels that each got.

#19 수정사항 반영
  localisation/parties_l_english.yml
  localisation/replace/replace_countries_cosmetic_l_english.yml
  localisation/ww1_cosmetic_tags_l_english.yml
  localisation/ww1_events_australia_l_english.yml
  localisation/ww1_events_l_english.yml
  localisation/ww1_ideas_l_english.yml
Labels: 추가

#20 Update ww1_decisions_l_english.yml
  localisation/ww1_decisions_l_english.yml
Labels: 개선

#22 Update ww1_events_l_english.yml
  localisation/ww1_events_l_english.yml
Labels: 개선, 오역
