Repository Frosty1940/The-Great-War-Redux-Korean, pull requests merged in 2020-09, with the labels that each got.

#1 Update parties_l_english.yml
  localisation/parties_l_english.yml
Labels: 번역 개선, 추가 번역

#6 이벤트 번역 수정
  localisation/bookmarks_l_english.yml
  localisation/replace/replace_loading_tips_l_english.yml
  localisation/ww1_events_l_english.yml
Labels: 번역 개선

#3 Update ww1_factions_l_english.yml
  localisation/ww1_factions_l_english.yml
Labels: 번역 개선

#4 Update ww1_focus_l_english.yml
  localisation/ww1_focus_l_english.yml
Labels: 번역 개선

#5 Update ww1_ideas_l_english.yml
  localisation/ww1_ideas_l_english.yml
Labels: 번역 개선

#8 Update ww1_nf_uk_l_english.yml
  localisation/ww1_nf_uk_l_english.yml
Labels: 추가

#9 Update ww1_bookmarks_l_english.yml
  localisation/ww1_bookmarks_l_english.yml
Labels: 추가

#10 Update ww1_events_l_english.yml
  localisation/ww1_events_l_english.yml
Labels: 추가
